
package edu.touchard.simclavier;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Philippe SIMIER Lycée Touchard le Mans
 * @description Simulateur Clavier Digicode
 */
public class FenClavier extends javax.swing.JFrame {

    /**
     * Creates new form FenClavier
     */
    public FenClavier() {
        initComponents();
        touche0.addActionListener(new GestionnaireTouche());
        touche1.addActionListener(new GestionnaireTouche());
        touche2.addActionListener(new GestionnaireTouche());
        touche3.addActionListener(new GestionnaireTouche());
        touche4.addActionListener(new GestionnaireTouche());
        touche5.addActionListener(new GestionnaireTouche());
        touche6.addActionListener(new GestionnaireTouche());
        touche7.addActionListener(new GestionnaireTouche());
        touche8.addActionListener(new GestionnaireTouche());
        touche9.addActionListener(new GestionnaireTouche());
        //etoile.addActionListener(new GestionnaireTouche());
        //diese.addActionListener(new GestionnaireTouche());

    }

    private int compteurErreur = 0;
    private boolean bloque = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textMess = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        touche1 = new javax.swing.JButton();
        touche2 = new javax.swing.JButton();
        touche3 = new javax.swing.JButton();
        touche4 = new javax.swing.JButton();
        touche5 = new javax.swing.JButton();
        touche6 = new javax.swing.JButton();
        touche7 = new javax.swing.JButton();
        touche8 = new javax.swing.JButton();
        touche9 = new javax.swing.JButton();
        etoile = new javax.swing.JButton();
        touche0 = new javax.swing.JButton();
        diese = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(211, 211, 211));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Clavier"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(220, 250));

        textMess.setEditable(false);
        textMess.setBackground(new java.awt.Color(215, 215, 215));
        textMess.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textMess.setName("textMess"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(1, 1, 1));
        jPanel1.setLayout(new java.awt.GridLayout(4, 3, 1, 1));

        touche1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        touche1.setText("1");
        touche1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        touche1.setMaximumSize(new java.awt.Dimension(26, 26));
        touche1.setMinimumSize(new java.awt.Dimension(26, 26));
        touche1.setPreferredSize(new java.awt.Dimension(26, 26));
        jPanel1.add(touche1);

        touche2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        touche2.setText("2");
        touche2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        touche2.setMaximumSize(new java.awt.Dimension(26, 26));
        touche2.setMinimumSize(new java.awt.Dimension(26, 26));
        touche2.setPreferredSize(new java.awt.Dimension(26, 26));
        jPanel1.add(touche2);

        touche3.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        touche3.setText("3");
        touche3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        touche3.setMaximumSize(new java.awt.Dimension(26, 26));
        touche3.setMinimumSize(new java.awt.Dimension(26, 26));
        touche3.setPreferredSize(new java.awt.Dimension(26, 26));
        jPanel1.add(touche3);

        touche4.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        touche4.setText("4");
        touche4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        touche4.setMaximumSize(new java.awt.Dimension(26, 26));
        touche4.setMinimumSize(new java.awt.Dimension(26, 26));
        touche4.setPreferredSize(new java.awt.Dimension(26, 26));
        jPanel1.add(touche4);

        touche5.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        touche5.setText("5");
        touche5.setMargin(new java.awt.Insets(2, 2, 2, 2));
        touche5.setMaximumSize(new java.awt.Dimension(26, 26));
        touche5.setMinimumSize(new java.awt.Dimension(26, 26));
        touche5.setPreferredSize(new java.awt.Dimension(26, 26));
        jPanel1.add(touche5);

        touche6.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        touche6.setText("6");
        touche6.setMargin(new java.awt.Insets(2, 2, 2, 2));
        touche6.setMaximumSize(new java.awt.Dimension(26, 26));
        touche6.setMinimumSize(new java.awt.Dimension(26, 26));
        touche6.setPreferredSize(new java.awt.Dimension(26, 26));
        jPanel1.add(touche6);

        touche7.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        touche7.setText("7");
        touche7.setMargin(new java.awt.Insets(2, 2, 2, 2));
        touche7.setMaximumSize(new java.awt.Dimension(26, 26));
        touche7.setMinimumSize(new java.awt.Dimension(26, 26));
        touche7.setPreferredSize(new java.awt.Dimension(26, 26));
        jPanel1.add(touche7);

        touche8.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        touche8.setText("8");
        touche8.setMargin(new java.awt.Insets(2, 2, 2, 2));
        touche8.setMaximumSize(new java.awt.Dimension(26, 26));
        touche8.setMinimumSize(new java.awt.Dimension(26, 26));
        touche8.setPreferredSize(new java.awt.Dimension(26, 26));
        jPanel1.add(touche8);

        touche9.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        touche9.setText("9");
        touche9.setMargin(new java.awt.Insets(2, 2, 2, 2));
        touche9.setMaximumSize(new java.awt.Dimension(26, 26));
        touche9.setMinimumSize(new java.awt.Dimension(26, 26));
        touche9.setPreferredSize(new java.awt.Dimension(26, 26));
        jPanel1.add(touche9);

        etoile.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        etoile.setText("*");
        etoile.setMargin(new java.awt.Insets(2, 2, 2, 2));
        etoile.setMaximumSize(new java.awt.Dimension(26, 26));
        etoile.setMinimumSize(new java.awt.Dimension(26, 26));
        etoile.setPreferredSize(new java.awt.Dimension(26, 26));
        etoile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etoileMouseClicked(evt);
            }
        });
        jPanel1.add(etoile);

        touche0.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        touche0.setText("0");
        touche0.setMargin(new java.awt.Insets(2, 2, 2, 2));
        touche0.setMaximumSize(new java.awt.Dimension(26, 26));
        touche0.setMinimumSize(new java.awt.Dimension(26, 26));
        touche0.setPreferredSize(new java.awt.Dimension(26, 26));
        jPanel1.add(touche0);

        diese.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        diese.setText("#");
        diese.setMargin(new java.awt.Insets(2, 2, 2, 2));
        diese.setMaximumSize(new java.awt.Dimension(26, 26));
        diese.setMinimumSize(new java.awt.Dimension(26, 26));
        diese.setPreferredSize(new java.awt.Dimension(26, 26));
        diese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dieseMouseClicked(evt);
            }
        });
        jPanel1.add(diese);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textMess)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textMess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dieseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dieseMouseClicked
        textMess.setText("");
        textMess.setBackground(Color.LIGHT_GRAY);
        // Si le clavier est bloqué, alors fermeture
        if (bloque == true){
            System.exit(1);
        }
    }//GEN-LAST:event_dieseMouseClicked

    private void etoileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etoileMouseClicked

        if (textMess.getText().equals("1234")) {
            textMess.setBackground(Color.green);
            textMess.setText("Code Bon");
            compteurErreur = 0;
        } else {
            textMess.setBackground(Color.red);
            textMess.setText("Code Faux");
            compteurErreur++;
            if (compteurErreur >= 3) {
                textMess.setText("Clavier bloqué");
                bloque = true;
                
            }
        }
    }//GEN-LAST:event_etoileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenClavier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenClavier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenClavier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenClavier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenClavier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton diese;
    private javax.swing.JButton etoile;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textMess;
    private javax.swing.JButton touche0;
    private javax.swing.JButton touche1;
    private javax.swing.JButton touche2;
    private javax.swing.JButton touche3;
    private javax.swing.JButton touche4;
    private javax.swing.JButton touche5;
    private javax.swing.JButton touche6;
    private javax.swing.JButton touche7;
    private javax.swing.JButton touche8;
    private javax.swing.JButton touche9;
    // End of variables declaration//GEN-END:variables

    /*
       Le langage Java autorise la définition d’une classe 
       à l’intérieur d’une autre classe.
       Un des intérêts de cette notation est que la classe interne 
       GestionnaireTouche peut avoir accès aux méthodes et attributs 
       de la classe englobante FenClavier.
    */
    public class GestionnaireTouche implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            // recupération de l'objet à l'origine de l'évenement
            Object src = e.getSource();
            // si l'objet est un bouton et clavier pas bloqué
            if (src instanceof JButton && !bloque) {

                if (textMess.getText().length() < 4) {
                    // Récupérer le texte du bouton
                    String texteDeLaTouche = ((JButton) src).getText();
                    textMess.setText(textMess.getText() + texteDeLaTouche);
                }
            }
            
        }
    }

}
