/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diet;

/**
 *
 * @author cbourgouin
 */
public class PoidsIdeal extends javax.swing.JFrame {

    /**
     * Creates new form PoidsIdeal
     */
    private String nom;
    private String prenom;
    private double imc;
    private double poids;
    private double taille;
    private int age;
    final private double imcs[] = {16.5, 18.5, 25, 30, 35, 40};
    final private String corpulences[] = {"Famine", "Maigreur",
        "Normale", "Surpoids", "Obésité modérée", "Obésité sévère",
        "Obésité morbide"};
    final private int NBIMC = 6;
    final private int NBCORPULENCE = 7;
    private boolean infoVis;

    public PoidsIdeal() {
        initComponents();
        jPanelPoidsIdeal.setVisible(false);
        infoVis = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelPoidsIdeal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAfficheur = new javax.swing.JTextArea();
        jButtonDevine = new javax.swing.JButton();
        jButtonLorentz = new javax.swing.JButton();
        jButtonLorentzAge = new javax.swing.JButton();
        jPanelInformations = new javax.swing.JPanel();
        jPanelSexe = new javax.swing.JPanel();
        jRadioHomme = new javax.swing.JRadioButton();
        jRadioFemme = new javax.swing.JRadioButton();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jSpinnerAge = new javax.swing.JSpinner();
        jSpinnerPoids = new javax.swing.JSpinner();
        jSpinnerTaille = new javax.swing.JSpinner();
        jLabelNom = new javax.swing.JLabel();
        jLabelPrenom = new javax.swing.JLabel();
        jLabelSexe = new javax.swing.JLabel();
        jLabelAge = new javax.swing.JLabel();
        jLabelPoids = new javax.swing.JLabel();
        jLabelTaille = new javax.swing.JLabel();
        jButtonSuite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(530, 620));
        setResizable(false);

        jPanelPoidsIdeal.setBackground(java.awt.Color.lightGray);

        jTextAreaAfficheur.setColumns(20);
        jTextAreaAfficheur.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAfficheur);

        jButtonDevine.setText("Poids idéal devine");
        jButtonDevine.setOpaque(true);
        jButtonDevine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevineActionPerformed(evt);
            }
        });

        jButtonLorentz.setText("Poids idéal lorentz");
        jButtonLorentz.setOpaque(true);
        jButtonLorentz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLorentzActionPerformed(evt);
            }
        });

        jButtonLorentzAge.setText("Poids idéal lorentz / age");
        jButtonLorentzAge.setOpaque(true);
        jButtonLorentzAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLorentzAgeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPoidsIdealLayout = new javax.swing.GroupLayout(jPanelPoidsIdeal);
        jPanelPoidsIdeal.setLayout(jPanelPoidsIdealLayout);
        jPanelPoidsIdealLayout.setHorizontalGroup(
            jPanelPoidsIdealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPoidsIdealLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPoidsIdealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                    .addGroup(jPanelPoidsIdealLayout.createSequentialGroup()
                        .addGroup(jPanelPoidsIdealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonLorentz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDevine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonLorentzAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelPoidsIdealLayout.setVerticalGroup(
            jPanelPoidsIdealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPoidsIdealLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonDevine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLorentz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLorentzAge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelInformations.setBackground(new java.awt.Color(191, 191, 191));

        buttonGroup1.add(jRadioHomme);
        jRadioHomme.setText("Homme");
        jRadioHomme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioHommeActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioFemme);
        jRadioFemme.setText("Femme");

        javax.swing.GroupLayout jPanelSexeLayout = new javax.swing.GroupLayout(jPanelSexe);
        jPanelSexe.setLayout(jPanelSexeLayout);
        jPanelSexeLayout.setHorizontalGroup(
            jPanelSexeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSexeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioHomme)
                .addGap(18, 18, 18)
                .addComponent(jRadioFemme)
                .addGap(6, 6, 6))
        );
        jPanelSexeLayout.setVerticalGroup(
            jPanelSexeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSexeLayout.createSequentialGroup()
                .addGroup(jPanelSexeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioFemme)
                    .addComponent(jRadioHomme))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSpinnerAge.setModel(new javax.swing.SpinnerNumberModel(1, 1, 200, 1));
        jSpinnerAge.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSpinnerAge.setName(""); // NOI18N

        jSpinnerPoids.setModel(new javax.swing.SpinnerNumberModel(15.0d, 15.0d, 300.0d, 0.1d));

        jSpinnerTaille.setModel(new javax.swing.SpinnerNumberModel(0.5d, 0.5d, 3.0d, 0.01d));
        jSpinnerTaille.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelNom.setText("Nom");

        jLabelPrenom.setText("Prénom");

        jLabelSexe.setText("Sexe");

        jLabelAge.setText("Age");

        jLabelPoids.setText("Poids");

        jLabelTaille.setText("Taille");

        javax.swing.GroupLayout jPanelInformationsLayout = new javax.swing.GroupLayout(jPanelInformations);
        jPanelInformations.setLayout(jPanelInformationsLayout);
        jPanelInformationsLayout.setHorizontalGroup(
            jPanelInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInformationsLayout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(jPanelInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNom, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPrenom, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSexe, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelAge, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPoids, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTaille, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldPrenom)
                    .addComponent(jTextFieldNom)
                    .addComponent(jPanelSexe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(jSpinnerPoids)
                    .addComponent(jSpinnerTaille, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(jSpinnerAge))
                .addContainerGap())
        );
        jPanelInformationsLayout.setVerticalGroup(
            jPanelInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformationsLayout.createSequentialGroup()
                .addGroup(jPanelInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrenom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelSexe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSexe, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerPoids, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPoids))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerTaille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTaille))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonSuite.setText("Suite");
        jButtonSuite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jButtonSuite, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelPoidsIdeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jPanelInformations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanelInformations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSuite)
                .addGap(24, 24, 24)
                .addComponent(jPanelPoidsIdeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioHommeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioHommeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioHommeActionPerformed

    private void jButtonSuiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuiteActionPerformed
        poids = (double) jSpinnerPoids.getValue();
        age = (int) jSpinnerAge.getValue();
        nom = jTextFieldNom.getText();
        prenom = jTextFieldPrenom.getText();
        taille = (double) jSpinnerTaille.getValue();
        jTextAreaAfficheur.append("\nBonjour " + prenom + " " + nom);
        imc = (double) poids / (taille*taille);
        jTextAreaAfficheur.append("\nVotre indice de masse corporel est de: " + imc);
        int indiceCorpulence = 0;
        for (int i = 0; i < NBIMC - 1; i++) {
            if (imc > imcs[i] && imc <= imcs[i + 1]) {
                indiceCorpulence = i + 1;
            }
        }
// cas extreme
        if (imc < 16.5) {
            indiceCorpulence = 0;
        }
        if (imc > 40) {
            indiceCorpulence = NBCORPULENCE - 1;
        }
        jTextAreaAfficheur.append("\nVotre corpulence est qualifiée de " + corpulences[indiceCorpulence]);
        
        if(infoVis == true){
            jPanelPoidsIdeal.setVisible(true);
            jPanelInformations.setVisible(false);
            infoVis = false;
        } else {
            jPanelPoidsIdeal.setVisible(false);
            jPanelInformations.setVisible(true);
            infoVis = true;
        }


    }//GEN-LAST:event_jButtonSuiteActionPerformed

    private void jButtonDevineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevineActionPerformed
        double poidsIdeal = 0;
        if (jRadioFemme.isSelected()) {
            poidsIdeal = 45.5 + 2.3 * (taille / 0.0254 - 60.0);
        }
        if (jRadioHomme.isSelected()) {
            poidsIdeal = 50.0 + 2.3 * (taille / 0.0254 - 60.0);
        }
        if (poidsIdeal > 0) {
            jTextAreaAfficheur.append("\nVotre poids ideal avec la formule de devine : " + ((Double) poidsIdeal).toString() + " kg\n");
            double ecart = poids - poidsIdeal;
            if (ecart >= 0) {
                jTextAreaAfficheur.append("\nVous devez perdre " + ((Double) ecart).toString() + " kg\n");
            } else {
                jTextAreaAfficheur.append("\nVous devez prendre " + ((Double) (-ecart)).toString() + " kg\n");
            }
        }
    }//GEN-LAST:event_jButtonDevineActionPerformed

    private void jButtonLorentzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLorentzActionPerformed
        double poidsIdeal = 0;
        if (jRadioFemme.isSelected()) {
            poidsIdeal = taille*100-100-(taille*100-150)/2.5;
        }
        if (jRadioHomme.isSelected()) {
            poidsIdeal = taille*100-100-(taille*100-150)/4;
        }
        if (poidsIdeal > 0) {
            jTextAreaAfficheur.append("\nVotre poids ideal avec la formule de lorentz : " + ((Double) poidsIdeal).toString() + " kg\n");
            double ecart = poids - poidsIdeal;
            if (ecart >= 0) {
                jTextAreaAfficheur.append("\nVous devez perdre " + ((Double) ecart).toString() + " kg\n");
            } else {
                jTextAreaAfficheur.append("\nVous devez prendre " + ((Double) (-ecart)).toString() + " kg\n");
            }
        }
    }//GEN-LAST:event_jButtonLorentzActionPerformed

    private void jButtonLorentzAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLorentzAgeActionPerformed
        double poidsIdeal = 0;
        
        poidsIdeal = 50 + (taille*100-150)/4 + (age - 20)/4;
        
        if (poidsIdeal > 0) {
            jTextAreaAfficheur.append("\nVotre poids ideal avec la formule de lorentz : " + ((Double) poidsIdeal).toString() + " kg\n");
            double ecart = poids - poidsIdeal;
            if (ecart >= 0) {
                jTextAreaAfficheur.append("\nVous devez perdre " + ((Double) ecart).toString() + " kg\n");
            } else {
                jTextAreaAfficheur.append("\nVous devez prendre " + ((Double) (-ecart)).toString() + " kg\n");
            }
        }
    }//GEN-LAST:event_jButtonLorentzAgeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PoidsIdeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PoidsIdeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PoidsIdeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PoidsIdeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PoidsIdeal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonDevine;
    private javax.swing.JButton jButtonLorentz;
    private javax.swing.JButton jButtonLorentzAge;
    private javax.swing.JButton jButtonSuite;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPoids;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelSexe;
    private javax.swing.JLabel jLabelTaille;
    private javax.swing.JPanel jPanelInformations;
    private javax.swing.JPanel jPanelPoidsIdeal;
    private javax.swing.JPanel jPanelSexe;
    private javax.swing.JRadioButton jRadioFemme;
    private javax.swing.JRadioButton jRadioHomme;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerAge;
    private javax.swing.JSpinner jSpinnerPoids;
    private javax.swing.JSpinner jSpinnerTaille;
    private javax.swing.JTextArea jTextAreaAfficheur;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    // End of variables declaration//GEN-END:variables

    private void append(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
